version: '3.1'
services: 
    db:
        image: mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: otdel_kadrov
        volumes:
            - ./db :/docker-entrypoint-initdb.d    
     
    otdel:
        build: .
        restart: always
        links:
            - "db:database"
        ports: 
            - 8000:8000
        command: php -S 0.0.0.0:8000

